package org.faithfarm.domain;

// Generated Nov 9, 2013 3:11:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GiftType generated by hbm2java
 */
public class GiftType implements java.io.Serializable {

	private Long giftTypeId;
	private String name;
	private Set giftPledges = new HashSet(0);

	public GiftType() {
	}

	public GiftType(String name, Set giftPledges) {
		this.name = name;
		this.giftPledges = giftPledges;
	}

	public Long getGiftTypeId() {
		return this.giftTypeId;
	}

	public void setGiftTypeId(Long giftTypeId) {
		this.giftTypeId = giftTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getGiftPledges() {
		return this.giftPledges;
	}

	public void setGiftPledges(Set giftPledges) {
		this.giftPledges = giftPledges;
	}

}
