package org.faithfarm.domain;

// Generated Nov 25, 2013 11:59:15 AM by Hibernate Tools 4.0.0

/**
 * GiftPledge generated by hbm2java
 */
public class GiftPledge implements java.io.Serializable {

	private Long giftPledgeId;
	private GiftType giftType=new GiftType();
	private String giftDate;
	private Double pledgedAmount;
	private Double receivedAmount;
	private Double nonDeductibleAmount;
	private Long fundId;
	private Long campaignId;
	private Long approachId;
	private Long letterId;
	private String receipt;
	private String note;
	private String createdBy;
	private Integer creationDate;
	private String finalFlag;

	public GiftPledge() {
	}

	public GiftPledge(GiftType giftType) {
		this.giftType = giftType;
	}

	public GiftPledge(GiftType giftType, String giftDate, Double pledgedAmount,
			Double receivedAmount, Double nonDeductibleAmount, Long fundId,
			Long campaignId, Long approachId, Long letterId, String receipt,
			String note, String createdBy, Integer creationDate,
			String finalFlag) {
		this.giftType = giftType;
		this.giftDate = giftDate;
		this.pledgedAmount = pledgedAmount;
		this.receivedAmount = receivedAmount;
		this.nonDeductibleAmount = nonDeductibleAmount;
		this.fundId = fundId;
		this.campaignId = campaignId;
		this.approachId = approachId;
		this.letterId = letterId;
		this.receipt = receipt;
		this.note = note;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.finalFlag = finalFlag;
	}

	public Long getGiftPledgeId() {
		return this.giftPledgeId;
	}

	public void setGiftPledgeId(Long giftPledgeId) {
		this.giftPledgeId = giftPledgeId;
	}

	public GiftType getGiftType() {
		return this.giftType;
	}

	public void setGiftType(GiftType giftType) {
		this.giftType = giftType;
	}

	public String getGiftDate() {
		return this.giftDate;
	}

	public void setGiftDate(String giftDate) {
		this.giftDate = giftDate;
	}

	public Double getPledgedAmount() {
		return this.pledgedAmount;
	}

	public void setPledgedAmount(Double pledgedAmount) {
		this.pledgedAmount = pledgedAmount;
	}

	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	public Double getNonDeductibleAmount() {
		return this.nonDeductibleAmount;
	}

	public void setNonDeductibleAmount(Double nonDeductibleAmount) {
		this.nonDeductibleAmount = nonDeductibleAmount;
	}

	public Long getFundId() {
		return this.fundId;
	}

	public void setFundId(Long fundId) {
		this.fundId = fundId;
	}

	public Long getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}

	public Long getApproachId() {
		return this.approachId;
	}

	public void setApproachId(Long approachId) {
		this.approachId = approachId;
	}

	public Long getLetterId() {
		return this.letterId;
	}

	public void setLetterId(Long letterId) {
		this.letterId = letterId;
	}

	public String getReceipt() {
		return this.receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Integer creationDate) {
		this.creationDate = creationDate;
	}

	public String getFinalFlag() {
		return this.finalFlag;
	}

	public void setFinalFlag(String finalFlag) {
		this.finalFlag = finalFlag;
	}

}
