package org.faithfarm.domain;


// Generated Nov 9, 2013 3:11:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * GiftPledge generated by hbm2java
 */
public class GiftPledge implements java.io.Serializable {

	private Long giftPledgeId;
	private GiftType giftType=new GiftType();
	private String giftDate;
	private Double pledgedAmount;
	private Double receivedAmount;
	private Double nonDeductibleAmount;
	private Long fund;
	private Long campaign;
	private Long approach;
	private Long letter;
	private String receipt;
	private String note;
	private String createdBy;
	private Integer creationDate;
	private String finalFlag;

	public GiftPledge() {
	}

	public GiftPledge(GiftType giftType) {
		this.giftType = giftType;
	}

	public GiftPledge(GiftType giftType, String giftDate, Double pledgedAmount,
			Double receivedAmount, Double nonDeductibleAmount, Long fund,
			Long campaign, Long approach, Long letter, String receipt,
			String note, String createdBy, Integer creationDate,
			String finalFlag) {
		this.giftType = giftType;
		this.giftDate = giftDate;
		this.pledgedAmount = pledgedAmount;
		this.receivedAmount = receivedAmount;
		this.nonDeductibleAmount = nonDeductibleAmount;
		this.fund = fund;
		this.campaign = campaign;
		this.approach = approach;
		this.letter = letter;
		this.receipt = receipt;
		this.note = note;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.finalFlag = finalFlag;
	}

	public Long getGiftPledgeId() {
		return this.giftPledgeId;
	}

	public void setGiftPledgeId(Long giftPledgeId) {
		this.giftPledgeId = giftPledgeId;
	}

	public GiftType getGiftType() {
		return this.giftType;
	}

	public void setGiftType(GiftType giftType) {
		this.giftType = giftType;
	}

	public String getGiftDate() {
		return this.giftDate;
	}

	public void setGiftDate(String giftDate) {
		this.giftDate = giftDate;
	}

	public Double getPledgedAmount() {
		return this.pledgedAmount;
	}

	public void setPledgedAmount(Double pledgedAmount) {
		this.pledgedAmount = pledgedAmount;
	}

	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	public Double getNonDeductibleAmount() {
		return this.nonDeductibleAmount;
	}

	public void setNonDeductibleAmount(Double nonDeductibleAmount) {
		this.nonDeductibleAmount = nonDeductibleAmount;
	}

	public Long getFund() {
		return this.fund;
	}

	public void setFund(Long fund) {
		this.fund = fund;
	}

	public Long getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Long campaign) {
		this.campaign = campaign;
	}

	public Long getApproach() {
		return this.approach;
	}

	public void setApproach(Long approach) {
		this.approach = approach;
	}

	public Long getLetter() {
		return this.letter;
	}

	public void setLetter(Long letter) {
		this.letter = letter;
	}

	public String getReceipt() {
		return this.receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Integer creationDate) {
		this.creationDate = creationDate;
	}

	public String getFinalFlag() {
		return this.finalFlag;
	}

	public void setFinalFlag(String finalFlag) {
		this.finalFlag = finalFlag;
	}

} 
